In [4]:
import numpy as np
import tensorly as tl

import numpy as np
import tensorly as tl
tensor = tl.tensor(np.arange(12).reshape((3, 2, 2))) # 12 = 2 x2 x3
original_shape = tensor.shape

print('* original tensor:\n{}'.format(tensor))
print('original shape:')
print(original_shape)

* original tensor:
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
original shape:
(3, 2, 2)


In [5]:

from tensorly import unfold
from tensorly import fold


mode0_t2 = unfold(tensor, 0) # mode-1 unfolding = convert a tensor into a vector
print('* unfolded (mode-0) tensor:\n{}'.format(mode0_t2))

mode1_t2 = unfold(tensor, 1) # mode-2 unfolding
print('* unfolded (mode-1) tensor:\n{}'.format(mode1_t2))

mode2_t2 = unfold(tensor, 2) # mode-3 unfolding
print('* unfolded (mode-2) tensor:\n{}'.format(mode2_t2))


torig = fold(mode2_t2, 2, original_shape) # 2 is used to specify the mode.
print('* again original tensor:\n{}'.format(torig))


* unfolded (mode-0) tensor:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
* unfolded (mode-1) tensor:
[[ 0  1  4  5  8  9]
 [ 2  3  6  7 10 11]]
* unfolded (mode-2) tensor:
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
* again original tensor:
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [3]:
# khatri-rao product
import numpy as np
from scipy import linalg

a = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
b = np.array([['g', 'h', 'i'], ['j', 'k', 'l']])
linalg.khatri_rao(a, b)

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None